"""Abaqus / CalculiX ``.inp`` writer (keyword format shared by both)."""

from __future__ import annotations

from pathlib import Path
from typing import Iterable

from ...models import FEModel


def _chunks(ids: Iterable[int], n: int = 16) -> list[str]:
    ids = list(ids)
    return [", ".join(str(i) for i in ids[k:k + n]) for k in range(0, len(ids), n)]


def _element_type(model: FEModel) -> str:
    plane = "CPE" if model.spec.analysis == "PLANE_STRAIN" else "CPS"
    return f"{plane}{6 if model.mesh.order == 2 else 3}"


def _dof_ranges(dofs: tuple[int, ...]) -> list[tuple[int, int]]:
    d = sorted(dofs)
    if d == [1, 2]:
        return [(1, 2)]
    return [(x, x) for x in d]


def write_inp(model: FEModel, path: str | Path, dialect: str = "abaqus") -> Path:
    path = Path(path)
    mesh, spec = model.mesh, model.spec
    mat = spec.material
    out: list[str] = [
        "*HEADING",
        f"cad2fem: {spec.title} | {spec.analysis} | units mm, N, MPa, t/mm^3 | {dialect}",
        "** Generated by cad2fem multi-agent pipeline",
        f"** Source spec: {spec.source}; thickness {spec.thickness:g} mm",
        "*NODE, NSET=NALL",
    ]
    out += [f"{i + 1}, {x:.10g}, {y:.10g}" for i, (x, y) in enumerate(mesh.nodes)]
    out.append(f"*ELEMENT, TYPE={_element_type(model)}, ELSET=EALL")
    out += [f"{e + 1}, " + ", ".join(str(n + 1) for n in el) for e, el in enumerate(mesh.elements)]

    for name, ids in mesh.node_sets.items():
        if name == "NALL":
            continue
        out.append(f"*NSET, NSET={name}")
        out += _chunks(int(i) + 1 for i in ids)
    for name, faces in mesh.surfaces.items():
        by_face: dict[int, list[int]] = {}
        for e, f in faces:
            by_face.setdefault(f, []).append(e + 1)
        for f, els in by_face.items():
            out.append(f"*ELSET, ELSET={name}_S{f}")
            out += _chunks(els)
        if dialect == "abaqus":
            out.append(f"*SURFACE, NAME={name}, TYPE=ELEMENT")
            out += [f"{name}_S{f}, S{f}" for f in by_face]

    out += [f"*MATERIAL, NAME={mat.name}", "*ELASTIC", f"{mat.E:.8g}, {mat.nu:.6g}",
            "*DENSITY", f"{mat.density:.6g}",
            f"*SOLID SECTION, ELSET=EALL, MATERIAL={mat.name}", f"{spec.thickness:.8g},"]

    out += ["**", "*STEP", "*STATIC"]
    if model.constraints:
        out.append("*BOUNDARY")
        for name, dofs, value, desc in model.constraints:
            out.append(f"** {desc}")
            for a, b in _dof_ranges(dofs):
                out.append(f"{name}, {a}, {b}, {value:g}" if value else f"{name}, {a}, {b}")

    pressure_sets = {name for name, _ in model.pressures}
    if model.pressures and dialect == "abaqus":
        out.append("*DSLOAD")
        out += [f"{name}, P, {p:.8g}" for name, p in model.pressures]
    cload = [(n, f) for n, f in model.nodal_forces.items()
             if dialect != "abaqus" or n not in pressure_sets]
    if cload:
        out.append("*CLOAD")
        for name, forces in cload:
            out.append(f"** {name} (consistent nodal forces)")
            for nid, (fx, fy) in zip(mesh.node_sets[name], forces):
                if abs(fx) > 0:
                    out.append(f"{int(nid) + 1}, 1, {fx:.10g}")
                if abs(fy) > 0:
                    out.append(f"{int(nid) + 1}, 2, {fy:.10g}")

    if dialect == "abaqus":
        out += ["*OUTPUT, FIELD, VARIABLE=PRESELECT", "*OUTPUT, HISTORY, VARIABLE=PRESELECT"]
    else:
        out += ["*NODE FILE", "U, RF", "*EL FILE", "S, E"]
        for name, *_ in model.constraints:
            out += [f"*NODE PRINT, NSET={name}, TOTALS=YES", "RF"]
    out.append("*END STEP")
    path.write_text("\n".join(out) + "\n")
    return path


def write_abaqus(model: FEModel, path: str | Path) -> Path:
    """Pressures as *DSLOAD on element-based surfaces."""
    return write_inp(model, path, "abaqus")


def write_calculix(model: FEModel, path: str | Path) -> Path:
    """Pressures converted to consistent nodal forces (*CLOAD)."""
    return write_inp(model, path, "calculix")
